modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}

本模组由「来自太空的小头脑」开发（邮箱：lztkdxtn@qq.com）。
功能玩法仿照 Bukkit 插件 SuperHarvest（插件作者：Dru_TNT），并非官方移植，仅作单机/Forge 端连锁采集实现。'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
